version: '3'
services:
  cloud9:
    build: .
    volumes:
      - /workplace/mariodes/github/java-sorting-algorithms/:/workspace/java-sorting-algorithms/
      - gradle_cache:/workspace/java-sorting-algorithms/.gradle
    ports:
      - 80:80
      - 3000:3000
volumes:
  gradle_cache: